MOCK_TRAINS = [
    {"id": "TRN001", "name": "Taj Express", "train_number": "19951", "source": "Delhi", "source_code": "NDLS", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2043, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 86, "amenities": ["E-Catering", "Clean Bedding", "Charging Point", "Bio-Toilets"]},
    {"id": "TRN002", "name": "Rajdhani Express", "train_number": "17286", "source": "Lucknow", "source_code": "LKO", "destination": "Delhi", "destination_code": "NDLS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1199, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 92, "amenities": ["Clean Bedding", "Charging Point"]},
    {"id": "TRN003", "name": "Gomti Express", "train_number": "18463", "source": "Mumbai", "source_code": "BCT", "destination": "Jaipur", "destination_code": "JP", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2230, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 11, "amenities": ["Charging Point", "Clean Bedding"]},
    {"id": "TRN004", "name": "Vande Bharat Exp", "train_number": "13295", "source": "Lucknow", "source_code": "LKO", "destination": "Jaipur", "destination_code": "JP", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 803, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 78, "amenities": ["Pantry Car", "Bio-Toilets", "Charging Point"]},
    {"id": "TRN005", "name": "Gomti Express", "train_number": "12419", "source": "Bangalore", "source_code": "SBC", "destination": "Agra", "destination_code": "AGC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1391, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 23, "amenities": ["E-Catering", "Clean Bedding", "Bio-Toilets", "Pantry Car"]},
    {"id": "TRN006", "name": "Vande Bharat Exp", "train_number": "14648", "source": "Bangalore", "source_code": "SBC", "destination": "Delhi", "destination_code": "NDLS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1062, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 83, "amenities": ["Pantry Car", "Bio-Toilets", "Charging Point"]},
    {"id": "TRN007", "name": "Duronto Express", "train_number": "18720", "source": "Kanpur", "source_code": "CNB", "destination": "Agra", "destination_code": "AGC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 646, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 22, "amenities": ["E-Catering", "Bio-Toilets"]},
    {"id": "TRN008", "name": "Duronto Express", "train_number": "19822", "source": "Varanasi", "source_code": "BSB", "destination": "Agra", "destination_code": "AGC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2374, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 33, "amenities": ["E-Catering", "Bio-Toilets", "Charging Point", "Pantry Car"]},
    {"id": "TRN009", "name": "Rajdhani Express", "train_number": "13986", "source": "Lucknow", "source_code": "LKO", "destination": "Firozabad", "destination_code": "FZD", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 641, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 47, "amenities": ["E-Catering", "Charging Point", "Bio-Toilets"]},
    {"id": "TRN010", "name": "Kalindi Express", "train_number": "16098", "source": "Bangalore", "source_code": "SBC", "destination": "Pune", "destination_code": "PUNE", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 835, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 90, "amenities": ["Bio-Toilets", "Charging Point", "E-Catering"]},
    {"id": "TRN011", "name": "Shatabdi Express", "train_number": "11591", "source": "Hyderabad", "source_code": "HYB", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 944, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 93, "amenities": ["Bio-Toilets", "Clean Bedding"]},
    {"id": "TRN012", "name": "Intercity Exp", "train_number": "14519", "source": "Delhi", "source_code": "NDLS", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 693, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 81, "amenities": ["Clean Bedding", "Charging Point"]},
    {"id": "TRN013", "name": "Taj Express", "train_number": "19351", "source": "Hyderabad", "source_code": "HYB", "destination": "Lucknow", "destination_code": "LKO", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1378, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 30, "amenities": ["E-Catering", "Clean Bedding", "Charging Point"]},
    {"id": "TRN014", "name": "Kalindi Express", "train_number": "19465", "source": "Varanasi", "source_code": "BSB", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 490, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 18, "amenities": ["Bio-Toilets", "E-Catering", "Pantry Car"]},
    {"id": "TRN015", "name": "Duronto Express", "train_number": "17876", "source": "Jaipur", "source_code": "JP", "destination": "Delhi", "destination_code": "NDLS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 447, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 21, "amenities": ["Bio-Toilets", "Pantry Car", "Charging Point", "E-Catering"]},
    {"id": "TRN016", "name": "Kalindi Express", "train_number": "16703", "source": "Pune", "source_code": "PUNE", "destination": "Jaipur", "destination_code": "JP", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1694, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 69, "amenities": ["Bio-Toilets", "Pantry Car", "Charging Point"]},
    {"id": "TRN017", "name": "Rajdhani Express", "train_number": "17546", "source": "Bangalore", "source_code": "SBC", "destination": "Firozabad", "destination_code": "FZD", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1683, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 17, "amenities": ["Pantry Car", "Clean Bedding", "E-Catering"]},
    {"id": "TRN018", "name": "Shatabdi Express", "train_number": "13605", "source": "Lucknow", "source_code": "LKO", "destination": "Kanpur", "destination_code": "CNB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2303, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 50, "amenities": ["E-Catering", "Bio-Toilets", "Charging Point"]},
    {"id": "TRN019", "name": "Duronto Express", "train_number": "14527", "source": "Firozabad", "source_code": "FZD", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 891, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 17, "amenities": ["Bio-Toilets", "E-Catering", "Charging Point"]},
    {"id": "TRN020", "name": "Vande Bharat Exp", "train_number": "15025", "source": "Bangalore", "source_code": "SBC", "destination": "Pune", "destination_code": "PUNE", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 887, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 12, "amenities": ["Bio-Toilets", "Pantry Car"]},
    {"id": "TRN021", "name": "Kalindi Express", "train_number": "16112", "source": "Varanasi", "source_code": "BSB", "destination": "Kochi", "destination_code": "ERS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1249, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 18, "amenities": ["Bio-Toilets", "Charging Point", "E-Catering", "Pantry Car"]},
    {"id": "TRN022", "name": "Gomti Express", "train_number": "15792", "source": "Pune", "source_code": "PUNE", "destination": "Kochi", "destination_code": "ERS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 502, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 88, "amenities": ["Clean Bedding", "Charging Point", "Bio-Toilets", "Pantry Car"]},
    {"id": "TRN023", "name": "Intercity Exp", "train_number": "15549", "source": "Firozabad", "source_code": "FZD", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1337, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 14, "amenities": ["Pantry Car", "Charging Point", "Clean Bedding", "Bio-Toilets"]},
    {"id": "TRN024", "name": "Rajdhani Express", "train_number": "14677", "source": "Kochi", "source_code": "ERS", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1069, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 100, "amenities": ["Bio-Toilets", "E-Catering", "Clean Bedding", "Charging Point"]},
    {"id": "TRN025", "name": "Shatabdi Express", "train_number": "18613", "source": "Bangalore", "source_code": "SBC", "destination": "Pune", "destination_code": "PUNE", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2373, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 100, "amenities": ["Charging Point", "Pantry Car", "Clean Bedding"]},
    {"id": "TRN026", "name": "Vande Bharat Exp", "train_number": "11937", "source": "Kochi", "source_code": "ERS", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1536, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 41, "amenities": ["Charging Point", "E-Catering", "Pantry Car", "Bio-Toilets"]},
    {"id": "TRN027", "name": "Rajdhani Express", "train_number": "18965", "source": "Agra", "source_code": "AGC", "destination": "Jaipur", "destination_code": "JP", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1703, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 45, "amenities": ["E-Catering", "Charging Point", "Bio-Toilets", "Clean Bedding"]},
    {"id": "TRN028", "name": "Taj Express", "train_number": "19623", "source": "Bangalore", "source_code": "SBC", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1154, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 54, "amenities": ["Charging Point", "Pantry Car", "Bio-Toilets", "Clean Bedding"]},
    {"id": "TRN029", "name": "Intercity Exp", "train_number": "19510", "source": "Varanasi", "source_code": "BSB", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1279, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 10, "amenities": ["Clean Bedding", "Pantry Car", "E-Catering", "Bio-Toilets"]},
    {"id": "TRN030", "name": "Shatabdi Express", "train_number": "12080", "source": "Mumbai", "source_code": "BCT", "destination": "Firozabad", "destination_code": "FZD", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2076, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 12, "amenities": ["Clean Bedding", "Pantry Car", "E-Catering", "Bio-Toilets"]},
    {"id": "TRN031", "name": "Intercity Exp", "train_number": "17131", "source": "Agra", "source_code": "AGC", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2013, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 66, "amenities": ["Clean Bedding", "Bio-Toilets", "Pantry Car"]},
    {"id": "TRN032", "name": "Duronto Express", "train_number": "14442", "source": "Jaipur", "source_code": "JP", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2253, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 99, "amenities": ["Pantry Car", "E-Catering", "Clean Bedding", "Bio-Toilets"]},
    {"id": "TRN033", "name": "Gomti Express", "train_number": "17380", "source": "Agra", "source_code": "AGC", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1511, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 62, "amenities": ["Clean Bedding", "Pantry Car"]},
    {"id": "TRN034", "name": "Duronto Express", "train_number": "14116", "source": "Pune", "source_code": "PUNE", "destination": "Agra", "destination_code": "AGC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1165, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 75, "amenities": ["E-Catering", "Pantry Car", "Bio-Toilets"]},
    {"id": "TRN035", "name": "Gomti Express", "train_number": "18914", "source": "Lucknow", "source_code": "LKO", "destination": "Kochi", "destination_code": "ERS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1302, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 86, "amenities": ["E-Catering", "Clean Bedding"]},
    {"id": "TRN036", "name": "Rajdhani Express", "train_number": "18147", "source": "Varanasi", "source_code": "BSB", "destination": "Lucknow", "destination_code": "LKO", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1178, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 25, "amenities": ["Charging Point", "Clean Bedding", "Pantry Car", "Bio-Toilets"]},
    {"id": "TRN037", "name": "Kalindi Express", "train_number": "19239", "source": "Pune", "source_code": "PUNE", "destination": "Kochi", "destination_code": "ERS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 683, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 17, "amenities": ["Charging Point", "Bio-Toilets", "Clean Bedding", "E-Catering"]},
    {"id": "TRN038", "name": "Taj Express", "train_number": "15762", "source": "Delhi", "source_code": "NDLS", "destination": "Varanasi", "destination_code": "BSB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 853, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 98, "amenities": ["Charging Point", "E-Catering", "Bio-Toilets", "Clean Bedding"]},
    {"id": "TRN039", "name": "Shatabdi Express", "train_number": "11612", "source": "Varanasi", "source_code": "BSB", "destination": "Agra", "destination_code": "AGC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1515, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 73, "amenities": ["E-Catering", "Clean Bedding"]},
    {"id": "TRN040", "name": "Rajdhani Express", "train_number": "11482", "source": "Bangalore", "source_code": "SBC", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1352, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 61, "amenities": ["Clean Bedding", "Bio-Toilets", "Charging Point", "Pantry Car"]},
    {"id": "TRN041", "name": "Rajdhani Express", "train_number": "13191", "source": "Firozabad", "source_code": "FZD", "destination": "Mumbai", "destination_code": "BCT", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 350, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 27, "amenities": ["Bio-Toilets", "Clean Bedding", "E-Catering", "Charging Point"]},
    {"id": "TRN042", "name": "Taj Express", "train_number": "14553", "source": "Delhi", "source_code": "NDLS", "destination": "Jaipur", "destination_code": "JP", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1517, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 73, "amenities": ["Clean Bedding", "Bio-Toilets", "E-Catering"]},
    {"id": "TRN043", "name": "Intercity Exp", "train_number": "17600", "source": "Mumbai", "source_code": "BCT", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1856, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 73, "amenities": ["Pantry Car", "Clean Bedding", "E-Catering", "Charging Point"]},
    {"id": "TRN044", "name": "Taj Express", "train_number": "12990", "source": "Kochi", "source_code": "ERS", "destination": "Varanasi", "destination_code": "BSB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 501, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 10, "amenities": ["Charging Point", "Clean Bedding", "E-Catering"]},
    {"id": "TRN045", "name": "Kalindi Express", "train_number": "11336", "source": "Delhi", "source_code": "NDLS", "destination": "Bangalore", "destination_code": "SBC", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2256, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 82, "amenities": ["Bio-Toilets", "Pantry Car"]},
    {"id": "TRN046", "name": "Shatabdi Express", "train_number": "13910", "source": "Lucknow", "source_code": "LKO", "destination": "Delhi", "destination_code": "NDLS", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2498, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 48, "amenities": ["Bio-Toilets", "Charging Point", "E-Catering", "Clean Bedding"]},
    {"id": "TRN047", "name": "Gomti Express", "train_number": "13198", "source": "Hyderabad", "source_code": "HYB", "destination": "Firozabad", "destination_code": "FZD", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1861, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 44, "amenities": ["Clean Bedding", "E-Catering", "Pantry Car"]},
    {"id": "TRN048", "name": "Kalindi Express", "train_number": "11197", "source": "Hyderabad", "source_code": "HYB", "destination": "Pune", "destination_code": "PUNE", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1612, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 93, "amenities": ["Charging Point", "E-Catering", "Bio-Toilets"]},
    {"id": "TRN049", "name": "Taj Express", "train_number": "13094", "source": "Agra", "source_code": "AGC", "destination": "Hyderabad", "destination_code": "HYB", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 399, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 72, "amenities": ["Charging Point", "Bio-Toilets", "Clean Bedding", "E-Catering"]},
    {"id": "TRN050", "name": "Gomti Express", "train_number": "16787", "source": "Pune", "source_code": "PUNE", "destination": "Firozabad", "destination_code": "FZD", "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 2398, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 41, "amenities": ["E-Catering", "Charging Point", "Bio-Toilets", "Pantry Car"]}
]

def search_trains(source: str, destination: str, date: str, passengers: int):
    results = []
    for t in MOCK_TRAINS:
        if source.lower() in t["source"].lower() and destination.lower() in t["destination"].lower():
            results.append(t)
    if not results and source and destination:
        results.append({"id": "TRN-FALLBACK", "name": "TripPilot Express", "train_number": "19900", "source": source, "source_code": source[:3].upper(), "destination": destination, "destination_code": destination[:3].upper(), "departure": "08:00", "arrival": "18:00", "duration": "10h 00m", "price": 1200, "classes": ["1AC", "2AC", "3AC", "Sleeper"], "available_seats": 100, "amenities": ["Clean Bedding", "Pantry Car"], "is_demo": True})
    return results
